# Copyright (C) 2021 Julian Valentin, lsp-cli-plus Development Community
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: "CI"

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  build:
    name: "CI - Build Job"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"

      - name: "Set up Java"
        uses: "actions/setup-java@v4"
        with:
          distribution: "temurin"
          java-version: "21"

      - name: "Build lsp-cli-plus"
        run: "mvn -B -e verify"

  validate:
    name: "CI - Validate Job"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"

      - name: "Install Python Dependencies"
        run: "python -m pip install --upgrade pip && pip install xmlschema"

      - name: "Validate .assembly.xml"
        run: "python -u -c 'import xmlschema; xmlschema.XMLSchema(\"schemas/assembly-2.1.0.xsd\").validate(\".assembly.xml\")'"

      - name: "Validate changelog.xml"
        run: "python -u -c 'import xmlschema; xmlschema.XMLSchema(\"schemas/changes-1.0.0.xsd\").validate(\"changelog.xml\")'"

      - name: "Validate pom.xml"
        run: "python -u -c 'import xmlschema; xmlschema.XMLSchema(\"schemas/maven-4.0.0.xsd\").validate(\"pom.xml\")'"

  deploy:
    name: "CI - Deploy Job"
    needs:
      - "build"
      - "validate"
    if: "${{ startsWith(github.ref, 'refs/tags/') }}"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"

      - name: "Set up Java"
        uses: "actions/setup-java@v4"
        with:
          distribution: "temurin"
          java-version: "21"

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"

      - name: "Install Python Dependencies"
        run: "python -m pip install --upgrade pip && pip install semver"

      - name: "Set LSP_CLI_PLUS_VERSION"
        run: "echo \"LSP_CLI_PLUS_VERSION=$(python -c \"import re; print(re.search(r'<version>(.*?)</version>', open('pom.xml', 'r').read()).group(1), end='')\")\" >> $GITHUB_ENV"

      - name: "Check LSP_CLI_PLUS_VERSION"
        run: "if [[ -z \"$LSP_CLI_PLUS_VERSION\" ]]; then echo 'Error: LSP_CLI_PLUS_VERSION not set!'; (exit 1); fi; echo \"LSP_CLI_PLUS_VERSION set to '$LSP_CLI_PLUS_VERSION'\""

      - name: "Set LSP_CLI_IS_PRERELEASE"
        run: "if [[ -z \"$LSP_CLI_PLUS_VERSION\" ]]; then echo 'Error: LSP_CLI_PLUS_VERSION not set!'; (exit 1); fi; echo \"LSP_CLI_IS_PRERELEASE=$(python -c \"import semver; print('true' if semver.VersionInfo.parse('$LSP_CLI_PLUS_VERSION').prerelease is not None else 'false', end='')\")\" >> $GITHUB_ENV"

      - name: "Check LSP_CLI_IS_PRERELEASE"
        run: "if [[ -z \"$LSP_CLI_IS_PRERELEASE\" ]]; then echo 'Error: LSP_CLI_IS_PRERELEASE not set!'; (exit 1); fi; echo \"LSP_CLI_IS_PRERELEASE set to '$LSP_CLI_IS_PRERELEASE'\""

      - name: "Set LSP_CLI_CHANGELOG"
        run: "if [ \"$LSP_CLI_IS_PRERELEASE\" = \"false\" ]; then echo \"LSP_CLI_CHANGELOG<<EOF\" >> $GITHUB_ENV; python tools/convertChangelog.py --xml-file changelog.xml --version latest >> $GITHUB_ENV; echo \"EOF\" >> $GITHUB_ENV; else echo \"LSP_CLI_CHANGELOG=This is a pre-release. Use at your own risk.\" >> $GITHUB_ENV; fi"

      - name: "Build lsp-cli-plus"
        run: "mvn -B -e package"

      - name: "Create Binary Archives"
        run: "python tools/createBinaryArchives.py"

      - name: "Create GitHub Release"
        uses: "softprops/action-gh-release@v2"
        with:
          prerelease: "${{ env.LSP_CLI_IS_PRERELEASE }}"
          body: "${{ env.LSP_CLI_CHANGELOG }}"
          files: "target/lsp-cli-plus-${{ env.LSP_CLI_PLUS_VERSION }}.tar.gz\ntarget/lsp-cli-plus-${{ env.LSP_CLI_PLUS_VERSION }}-linux-x64.tar.gz\ntarget/lsp-cli-plus-${{ env.LSP_CLI_PLUS_VERSION }}-mac-x64.tar.gz\ntarget/lsp-cli-plus-${{ env.LSP_CLI_PLUS_VERSION }}-windows-x64.zip"
