name: Issue and pull request assignment

on:
    issues:
        types: [opened]
    pull_request:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - name: Auto-assign issue and pull request
              uses: pozil/auto-assign-issue@v2
              with:
                  assignees: spitzerd
